### ISSUE TITLE
Папка scripts

### ISSUE THREAD

**Issue by Krizis112** [MINDUSTRYRU/mod#31]
Создать папку scripts.

**Comment by MINDUSTRYRU** [comment]
Перейдите в папку, внутри которой вы хотите создать другую папку(либо в главную деррикторию)

Нажмите на новый файл

В текстовом поле для имени файла сначала напишите имя папки, которую вы хотите создать

Затем введите / . Это создает папку

Вы можете добавить больше папок аналогично

Наконец, дайте новому файлу имя (например, .gitkeep которое обычно используется для отслеживания Git, в противном случае пустые папки удалятся)

Наконец, нажмите кнопку « Применить новый файл» и создайте pull
